language: java
dist: trusty

# os:
#   - linux
#   - osx
# jdk:
#   - openjdk9
#   - openjdk10
#   - openjdk11
#   - openjdk-ea
#   - oraclejdk-ea

jobs:
  include:
    - os: linux
      jdk: openjdk8
  allow_failures:
    - os: osx
      jdk: oraclejdk8
# OSX: While Mac jobs can test against multiple JDK versions using the jdk key,
# macOS images up to xcode9.3 can only switch up to Java 8, and
# images xcode9.4 and later can switch to Java 10 (if pre-installed) and later

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew

notifications:
  email:
    on_success: never