name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Test Python
        run: |
          cd src/main/python
          python3 charts.py
          python3 sample.py 
      - name: Test Gradle
        run: |
          sudo apt install openjdk-8-jdk
          sudo update-alternatives --config java
          java -version
          chmod +x ./gradlew
          ./gradlew
